name = "catmash"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "catmash-db"
database_id = "6bc4eaa5-6aa7-473f-b337-dcee4d628351"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "catmash-images"
